name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  build-plugin:
    runs-on: macos-latest
    outputs:
      asset_path: ${{ steps.pack.outputs.asset_path }}
      asset_name: ${{ steps.pack.outputs.asset_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install IINA
        run: |
          brew install --cask iina

      - name: Pack plugin
        id: pack
        run: |
          rm -f *.iinaplgz
          /Applications/IINA.app/Contents/MacOS/iina-plugin pack .
          PLUGIN_FILE=$(ls *.iinaplgz)
          echo "asset_path=$PLUGIN_FILE" >> $GITHUB_OUTPUT
          echo "asset_name=$PLUGIN_FILE" >> $GITHUB_OUTPUT

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: iina-plugin
          path: ${{ steps.pack.outputs.asset_path }}

  create-release:
    runs-on: ubuntu-latest
    needs: build-plugin
    permissions:
      contents: write
    steps:
      - name: Download plugin artifact
        uses: actions/download-artifact@v4
        with:
          name: iina-plugin

      - name: Get version from tag
        id: get_version
        run: echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.tag_name }}
          name: ${{ steps.get_version.outputs.tag_name }}
          generate_release_notes: true
          prerelease: ${{ contains(steps.get_version.outputs.tag_name, '-') }}
          files: ${{ needs.build-plugin.outputs.asset_name }}
